
const EMAIL_CHANGED = 'email_changed';
const PASSWORD_CHANGED = 'password_changed';
const LOGIN_USER_SUCCESS = "login_user_success";
const LOGIN_USER_FAIL = "login_user_fail";
const LOGIN_USER = "login_user";
const EMPLOYEE_UPDATE = "empolyee_update";
const NAME_TEXT_CHANGE = "NAME_TEXT_CHANGE";
const PHONE_TEXT_CHANGE = "PHONE_TEXT_CHANGE";
const SHIFT_TEXT_CHANGE = "SHIFT_TEXT_CHANGE";
const CREATE_USER_EMPLOYEE = "CREATE_USER_EMPLOYEE";
const EMPLOYEE_FETCH_SUCCESS = "EMPLOYEE_FETCH_SUCCESS";


export { 

    EMAIL_CHANGED,
    PASSWORD_CHANGED, 
    LOGIN_USER_SUCCESS,
    LOGIN_USER_FAIL,
    LOGIN_USER,
    EMPLOYEE_UPDATE,
    NAME_TEXT_CHANGE,
    PHONE_TEXT_CHANGE,
    SHIFT_TEXT_CHANGE,
    CREATE_USER_EMPLOYEE,
    EMPLOYEE_FETCH_SUCCESS
};